#!/usr/bin/env python
# vim: set softtabstop=2 ts=2 sw=2 expandtab: 
#
# Copyright (c) 2015 Karl Vollmer (karl.vollmer@gmail.com)
#

import os,subprocess,sys,time,shutil
import ConfigParser
import json
import twitter
import tinyurl
from pymongo import MongoClient
from datetime import datetime
from tzlocal import get_localzone

def sendTweet(tweetText,levelType):

  """ If this is surf, send a surf tweet """
  if levelType == 'surf':
    sendSurfTweet(tweetText)

  """ Send a tweet """
  try: 
    api = twitter.Api(consumer_key=Config.get('twitter','consumer_key'),
      consumer_secret=Config.get('twitter','consumer_secret'),
      access_token_key=Config.get('twitter','access_token'),
      access_token_secret=Config.get('twitter','access_token_secret'))
  except:
    print 'Unable to connect to Twitter please verify your API credentials'
    return False

  try:
    api.PostUpdate(tweetText)
    print 'Tweeted %s to your account' % (tweetText)
    return True
  except:
    print 'Unable to send %s to twitter, tweet failure' % (tweetText)
    return False

def sendSurfTweet(tweetText):
  """ Send a tweet """
  try: 
    api = twitter.Api(consumer_key=Config.get('surftwitter','consumer_key'),
      consumer_secret=Config.get('surftwitter','consumer_secret'),
      access_token_key=Config.get('surftwitter','access_token'),
      access_token_secret=Config.get('surftwitter','access_token_secret'))
  except:
    print 'Unable to connect to Twitter please verify your API credentials'
    return False

  try:
    api.PostUpdate(tweetText)
    print 'Tweeted %s to your account' % (tweetText)
    return True
  except:
    print 'Unable to send %s to twitter, tweet failure' % (tweetText)
    return False


def runCmd(cmd):
  """ Run the command, and then wait for it to finish """
  proc = subprocess.Popen(cmd.split(),stdout=subprocess.PIPE,stderr=subprocess.STDOUT)
  proc.wait()

  if proc.returncode != 0:
    print 'Non-zero exit from %s ' % (cmd)
    return ''
  else:
    return proc.stdout.read()

def saveState(name,state,level):
  """ Save the current state to a file in ./state """
  timestamp = int(time.time())
  stateHandle = open(os.path.dirname(os.path.abspath(__file__)) + '/state/'+name,'w')
  stateHandle.write(json.dumps({'state':state,'lastTweet':timestamp,'level':level}))
  stateHandle.close()
  return True

def saveStatetoDB(name,state,run,data,runType):
  """ Get the Now time """
  now = datetime.now(get_localzone())

  if runType == 'surf':
    level_txt = str(data['level']) + str(data['level_info'])
  else:
    level_txt = data['level']

  data = { 'date': datetime.utcnow(),'name': name,'run' : run,'state': state,'level': data['level'], 'info': level_txt }

  """ Open a connection to the DB """
  client = MongoClient('localhost',27017)
  dbh = client['whitewaterns']
  result = dbh.leveldata.insert_one(data)

  return True

def saveStatetoImage(name,state,run,level):

  """ just Copy some files man this ain't rocket science """
  """ FIXME: should use same extension as source, but really you should be using png """
  target = Config.get('dashboard','target_dir') + '/' + name.replace(' ','') + run.replace(' ','') + '.png'
  source = Config.get('dashboard',state + '_image')
  try:
    shutil.copyfile(source,target)
  except:
    print 'Unable to copy %s to %s bummer' % (source,target)

  return True

""" Based on the Type, run whatever checks we should be running to determine if this is "UP" """
def isUp(state,sourceType,level):

  """ River Rules:
    - Above Min
    - Below Max
  """
  """ Surf Rules:
    - Above min
    - Below max
    - Period is higher than min
    - Between Min & Max direction
    - Between min & max tide point
    - Between min & max wind from Direction A-Z
  """
  """ Tidal Rules:
    - Above Min
    - Below Max
    - Between min & max tide point
  """
  if sourceType == 'river':
    if state['level'] < level['max'] and state['level'] >= level['min']:
      return True
  elif sourceType == 'surf':
    if (state['level'] < level['max'] and state['level'] >= level['min'] and
        state['direction'] < level['dirmax'] and state['direction'] >= level['dirmin'] and
        state['period'] > level['permin']):
      return True
  elif sourceType == 'tidal':
    return False

  return False

def isFlood(state,sourceType,level):

  """ Surf Rules:
    - too big of waves
    - bad direction
    - waves above min, but period below min
  """
  if sourceType == 'river':
    if state['level'] >= level['max']: 
      return True
  elif sourceType == 'surf':
    if (state['level'] >= level['max'] or state['direction'] < level['dirmin'] or state['direction'] > level ['dirmax'] or
        (state['level'] >= level['min'] and state['period'] < level['permin'])):
      return True

  return False

def isDown(state,sourceType,level):

  return False

def tweetMsg(name,location,data,state,sourceType):
  twitterText = ''

  if sourceType == 'river':
    if state == 'up':
      twitterText = '%s (%s) is up! Current Level %s' % (name,location,data['level'])
    elif state == 'down':
      twitterText = '%s (%s) is down, Current Level %s' % (name,location,data['level'])
    elif state == 'flood':
      twitterText = '%s (%s) is in flood, Current Level %s' % (name,location,data['level'])
  elif sourceType == 'surf':
    if state == 'up':
      twitterText = '%s is working, %s%s' % (location,data['level'],data['level_info'])
    elif state == 'down':
      twitterText = '%s is no longer working, %s%s' % (location,data['level'],data['level_info'])
    elif state == 'flood':
      twitterText = '%s is not ideal, %s%s' % (location,data['level'],data['level_info'])

  return twitterText

def checkLevels():
  sourceHandle = open(os.path.dirname(os.path.abspath(__file__)) + '/source.json')
  data = sourceHandle.read()
  sources = json.loads(data)
  for row in sources:
    cmd = os.path.dirname(os.path.abspath(__file__)) + '/bin/' + row['type'] + ' ' + row['source']
    cmdResults = runCmd(cmd)
    if len(cmdResults) == 0:
      """ If nothing returned jump to the next source """
      continue
    else:
      currentState = json.loads(cmdResults)

    """ Set default type to river if not defined """
    if 'level_type' in currentState:
      levelType = currentState['level_type']
    else:
      levelType = 'river'


    """ Now we need to figure out if we need to tweet something """
    for level in row['level']:
      stateName = row['uid']+level['name']
      """ Look for a previous state file """
      if os.path.exists(os.path.dirname(os.path.abspath(__file__)) + '/state/' + stateName):
        previousState = json.loads(open(os.path.dirname(os.path.abspath(__file__)) + '/state/' + stateName).read())
      else:
        previousState = { 'state':'down','lastTweet':int('0') }

      """ This could be simplifed by saveState() doing everything """
      if isUp(currentState,levelType,level):
        if previousState['state'] != 'up':
          sendTweet(tweetMsg(row['name'],level['name'],currentState,'up',levelType),levelType)        
          saveState(stateName,'up',currentState['level'])
          saveStatetoImage(row['name'],'up',level['name'],currentState['level'])
          saveStatetoDB(row['name'],'up',level['name'],currentState,levelType)
        elif (int(previousState['lastTweet'])+172800) <= int(time.time()):
          sendTweet(tweetMsg(row['name'],level['name'],currentState,'up',levelType),levelType)        
          saveState(stateName,'up',currentState['level'])
          saveStatetoImage(row['name'],'up',level['name'],currentState['level'])
          saveStatetoDB(row['name'],'up',level['name'],currentState,levelType)
      elif isFlood(currentState,levelType,level):
        if previousState['state'] != 'flood':
          sendTweet(tweetMsg(row['name'],level['name'],currentState,'flood',levelType),levelType)        
          saveState(stateName,'flood',currentState['level'])
          saveStatetoImage(row['name'],'flood',level['name'],currentState['level'])
          saveStatetoDB(row['name'],'flood',level['name'],currentState,levelType)
        elif (int(previousState['lastTweet'])+172800) <= int(time.time()):
          sendTweet(tweetMsg(row['name'],level['name'],currentState,'flood',levelType),levelType)        
          saveState(stateName,'flood',currentState['level'])
          saveStatetoImage(row['name'],'flood',level['name'],currentState['level'])
          saveStatetoDB(row['name'],'flood',level['name'],currentState,levelType)
      elif isDown(currentState,levelType,level):
        if previousState['state'] != 'down':
          sendTweet(tweetMsg(row['name'],level['name'],currentState,'down',levelType),levelType)        
          saveState(stateName,'down',currentState['level'])
          saveStatetoImage(row['name'],'down',level['name'],currentState['level'])
          saveStatetoDB(row['name'],'down',level['name'],currentState,levelType)
        elif (int(previousState['lastTweet'])+172800) <= int(time.time()):
          sendTweet(tweetMsg(row['name'],level['name'],currentState,'down',levelType),levelType)        
          saveState(stateName,'down',currentState['level'])
          saveStatetoImage(row['name'],'down',level['name'],currentState['level'])
          saveStatetoDB(row['name'],'down',level['name'],currentState,levelType)

if __name__ == '__main__':
  global Config
  """ Load the Config file ./settings.conf """
  Config = ConfigParser.ConfigParser()
  try:
    Config.read(os.path.dirname(os.path.abspath(__file__)) + '/settings.conf')
  except IOError:
    print ':Main:: IOError opening %s verify permissions' % (os.path.dirname(os.path.abspath(__file__)) + '/settings.conf')
    sys.exit(1)
  checkLevels()

